services:

  _defaults:
    public: false

  # Maker commands
  maker.maker.make_hexagonal_use_case:
      class: AdrienLbt\HexagonalMakerBundle\Maker\MakeHexagonalUseCase
      arguments: [
        '%hexagonal_maker.domain_path%'
      ]
      tags:
        - {name: 'maker.command'}